### ISSUE TITLE
Android N Crash

### ISSUE THREAD

**Issue by victordigio** [VitamioCustom/Vitamio-5.0.0#7]
I get this crash only on Android N when I play any audio with vitamio 5.0.1:

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.fivething.vietmobi, PID: 3404
java.lang.UnsatisfiedLinkError: No implementation found for void io.vov.vitamio.MediaPlayer.native_init() (tried Java_io_vov_vitamio_MediaPlayer_native_1init and Java_io_vov_vitamio_MediaPlayer_native_1init__)
at io.vov.vitamio.MediaPlayer.native_init(Native Method)
at io.vov.vitamio.MediaPlayer.(MediaPlayer.java:306)
at io.vov.vitamio.widget.VideoView.openVideo(VideoView.java:428)
at io.vov.vitamio.widget.VideoView.setVideoURI(VideoView.java:400)
at io.vov.vitamio.widget.VideoView.setVideoURI(VideoView.java:393)
at com.fivething.vietmobi.Player.e(Player.java:390)
at com.fivething.vietmobi.Player.c(Player.java:295)
at com.fivething.vietmobi.Player$2.onSuccess(Player.java:268)
at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:154)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:5969)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)

E/Vitamio[Player]: Error loading libs
java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: libstlport_shared.so
at java.lang.Runtime.load0(Runtime.java:889)
at java.lang.System.load(System.java:1505)
at io.vov.vitamio.MediaPlayer.load_lib(MediaPlayer.java:258)
at io.vov.vitamio.MediaPlayer.(MediaPlayer.java:319)
at io.vov.vitamio.widget.VideoView.openVideo(VideoView.java:428)
at io.vov.vitamio.widget.VideoView.setVideoURI(VideoView.java:400)
at io.vov.vitamio.widget.VideoView.setVideoURI(VideoView.java:393)
at com.fivething.vietmobi.Player.e(Player.java:390)
at com.fivething.vietmobi.Player.c(Player.java:295)
at com.fivething.vietmobi.Player$2.onSuccess(Player.java:268)
at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:154)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:5969)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)

**Comment by MythodeaLoL** [comment]
Vitamio is designed to max API 21. And they project is not optimized to Android 5+ Work on Android 5<.
R.I.P. Vitamio sorry, i dont have SDK to compile it.
